---
version: "3.8"

services:
  postgresql:
    image: docker.io/library/postgres:14.6
    container_name: postgresql
    restart: unless-stopped
    network_mode: bridge
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${SECRET_POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${SECRET_POSTGRESQL_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - /mnt/cache/appdata/postgresql/data:/var/lib/postgresql/data

  postgresql-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.11.1
    container_name: postgresql-exporter
    restart: unless-stopped
    network_mode: bridge
    environment:
      DATA_SOURCE_NAME: "postgresql://${SECRET_POSTGRESQL_USERNAME}:${SECRET_POSTGRESQL_PASSWORD}@pgsql-server:5432/postgres?sslmode=disable"
    ports:
      - 9187:9187
    links:
      - postgresql:pgsql-server

  pgadmin:
    image: docker.io/dpage/pgadmin4:6.15
    container_name: postgresql-pgadmin
    restart: unless-stopped
    network_mode: bridge
    environment:
      PGADMIN_DEFAULT_EMAIL: ${SECRET_PGADMIN_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${SECRET_PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 12080
    ports:
      - 12080:12080
    volumes:
      - /mnt/cache/appdata/postgresql/pgadmin:/var/lib/pgadmin
    links:
      - postgresql:pgsql-server
    depends_on:
      - postgresql

  pgbackups:
    image: docker.io/prodrigestivill/postgres-backup-local:16
    container_name: postgresql-pgbackups
    restart: unless-stopped
    network_mode: bridge
    environment:
      POSTGRES_HOST: pgsql-server
      POSTGRES_DB: postgres
      POSTGRES_USER: ${SECRET_POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${SECRET_POSTGRESQL_PASSWORD}
      POSTGRES_EXTRA_OPTS: "-Z9 --schema=public --blobs"
      SCHEDULE: "@daily"
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 0
      BACKUP_KEEP_MONTHS: 0
      HEALTHCHECK_PORT: 9166
    volumes:
      - /mnt/cache/appdata/postgresql/pgbackups:/backups
    links:
      - postgresql:pgsql-server
    depends_on:
      - postgresql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9166/"]
      interval: 30s
      timeout: 20s
      retries: 3

# volumes:
#   pg-data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: "/mnt/user/appdata/postgresql/data"
